### ISSUE TITLE
Internationalization on model property

### ISSUE THREAD

**Issue by franciscosucre** [adonisjs/adonis-antl#30]
Hi, i would like to be able to use certain fields objects in my database to fill selects in my App. I would like to have those objects with a constant name and use this library to format them. 

For this, i have written a getter for this property

```js
getName(name) {
    try {
      return Antl.formatMessage(`countries.${name}`)
    } catch (error) {
      Logger.error(error)
      return name
    }
  }
```

I would like to know if this would work en general cases. Specifically, i want to know if i can avoid using the http object because that would imply adding this format code to every place where this values al referenced. Sorry for the trouble and thanks for your anwser!

**Comment by thetutlage** [comment]
Hello!

Sorry for getting late on this. But using Antl directly on model will not be able to use the language defined within the HTTP request.

So ideally you can use the `Antl` class the way you are using. However, if your app relies on the HTTP lifecycle to decide the language of the user, then it will not work, since models are not aware of the HTTP requests data

Also, it's being a while for this issue, so I am not sure if you really need it now. I will close the issue, feel free to re-open and discuss more
