### ISSUE TITLE
Recursive directories

### ISSUE THREAD

**Issue by morheal** [adonisjs/adonis-antl#34]
How can I access locales if I have recursive directories?

For example, my folder structure my now is:

- resources
   -locales
      -en
         -admin
           -account
             -login.json

So how can I access login.json?

**Comment by thetutlage** [comment]
Nested directories are not supported, since the structure has to be portable across different drivers. For example: `Database driver` cannot have nested data.

We suggest keeping the file structure flat and use `dot notation` to scope string. For example:

**login.json**
```json
{
  "admin.account.login.emailLabel": ""
}
```

**Comment by morheal** [comment]
What about MongoDB? Would it be better do different wrappers for file locales and db locales?

Also shouldn't Facade (https://github.com/adonisjs/adonis-antl/blob/develop/src/Antl/Facade.js) loader() return an instance of loader as it said in comments? I can see that by now it returns just storage. If not , is there another way to get a loader itself?

**Comment by thetutlage** [comment]
Adonis out of the box doesn't support Mongo, so first level of care is given to the supported drivers.

Also the `facade` wraps the loader inside the `Antl` class, so that the loaders should have minimal API and all other operations are handled by the [Antl](https://github.com/adonisjs/adonis-antl/blob/develop/src/Antl/index.js) class.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
